scripts: build.sh: Add workaround for basehash value change SDK build issue
For G2L{C} SDK builds we are sometimes seeing the below issue:

ERROR: When reparsing *meta-environment.bb:do_generate_content, the
basehash value changed from x to y. The metadata is not deterministic and
this needs to be fixed.
ERROR: The following commands may help:
ERROR: $ bitbake meta-environment-smarc-rzg2l -cdo_generate_content -Snone
ERROR: Then:
ERROR: $ bitbake meta-environment-smarc-rzg2l -cdo_generate_content -Sprintdiff

Adding the above commands as a workaround until we can fix the SDK builds
in our environment.

Signed-off-by: Chris Paterson <chris.paterson2@renesas.com>